'use client';

import { FormEvent, useState } from 'react';
import { ImageResponseBase64 } from './api/generate/route';

export default function Home() {
  const [story, setStory] = useState('I once moved to New York and it was very lonely.');
  const [result, setResult] = useState('');
  const [imageURL, setImageURL] = useState('');

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();

    const response = await fetch('/api/generate', {
      method: 'POST',
      body: JSON.stringify({ story }),
    });

    const data: ImageResponseBase64 = await response.json();
    setResult(data.outputText);
    setImageURL(data.image);
  }

  return (
    <main className="p-6 max-w-2x1 mx-auto">
      <h1 className="text-2x1 font-bold mb-4">LifeMadeArt - MVP</h1>

      <form onSubmit={handleSubmit} className="flex flex-col gap-4">
        <textarea
          className="border p-3 rounded"
          rows={6}
          placeholder="Tell me your story..."
          value={story}
          onChange={(e) => setStory(e.target.value)}
        ></textarea>

        <button className="bg-black text-white p-3 rounded hover:bg-grey-800" type="submit">
          Generate
        </button>
      </form>

      {result && (
        <div className="mt-8 p-4 border rounded bg-grey-50">
          <h2 className="font-semibold mb-2">AI Output</h2>
          <p>{result}</p>
          <img src={imageURL} alt="image generated by AI" />
        </div>
      )}
    </main>
  );
}
